# Generated by Django 2.2 on 2020-07-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='站点名')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='联系方式')),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9, verbose_name='经度')),
                ('dimension', models.DecimalField(decimal_places=5, max_digits=9, verbose_name='维度')),
            ],
            options={
                'verbose_name': '站点信息',
                'verbose_name_plural': '站点信息',
            },
        ),
    ]
